name: .NET

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: server test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Install Report Generator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool
      - name: Restore dependencies
        working-directory: ./BudgetAmazon.Tests
        run: |
          dotnet restore BudgetAmazon.Tests.csproj
      - name: Build
        working-directory: ./BudgetAmazon.Tests
        run: |
          dotnet build --no-restore                     
      - name: Test
        working-directory: ./BudgetAmazon.Tests
        run: |
          dotnet test --no-build --collect:"XPlat Code Coverage" --verbosity normal
      - name: Generate Report
        working-directory: ./BudgetAmazon.Tests
        run: |
          cd TestResults
          cd "$(\ls -1dt ./*/ | head -n 1)"
          reportgenerator -reports:"coverage.cobertura.xml" -targetdir:"coveragereport" -reporttypes:Html
      - name: Uploading Artifact
        uses: actions/upload-artifact@v2
        with:
          name: testrun-result
          path: ./BudgetAmazon.Tests/TestResults