name: .NET

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: server test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5       
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1
      - name: Restore dependencies
        working-directory: ./BudgetAmazon
        run: |
          nuget restore BudgetAmazon.sln
      - name: Build
        working-directory: ./BudgetAmazon.Tests
        run: |
          msbuild BudgetAmazon.Tests.csproj /p:platform="AnyCPU" /p:configuration="Debug"
      - name: Test
        working-directory: ./BudgetAmazon.Tests
        run: |
          vstest.console.exe .\bin\Debug\BudgetAmazon.Tests.dll         